# Generated by Django 6.0 on 2026-05-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0077_tagconfig_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenbooking',
            name='appointment_medium',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('in_person', 'In Person')], default='in_person', max_length=50),
        ),
        migrations.AddField(
            model_name='tokenbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='tokenbooking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tokenbooking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
